# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convertible bond pricing.
#'
#' @param S_0 underlying initial price
#' @param sigma annualised implied volatility of the underlying
#' @param riskFreeInterestRate risk free rate
#' @param creditSpread spread to risk free rate
#' @param rateCompounding basis for rates. annual=1, semi-annual=2, etc. For the continious basis use rateCompounding=0
#' @param couponRate coupon on bond
#' @param couponFreq numer of coupons per year. Usually twice a year.
#' @param dividendProtectionRate divident protection threshold. In the model we use dividend protection via adjustment to conversion rate (Dividend protection is almost always provided by an adjustment to the conversion price or conversion ratio).
#' @param RDividendSchedule dividend schedule 2-column matrix. 1-column - time to dividend, 2-column - dividend rate. See demos.
#' @param conversionRatio number of shares per one convertible bond
#' @param noConversionPeriod restriction for conversion in years.
#' @param americanConversionType type of the conversion option. In almost all cases it is american. So we can convert any time. Set =0 if conversion possible only at maturity.
#' @param maturity maturity of the convertible
#' @param faceValue nominal amount of convertible bond
#' @param redemptionPremium premium at conversion. For example if issuer can pay premium 10% of the faceValue at maturity to the holder (at redemtion). If so set parameter =0.1. In almost all cases there is no redemption premium.
#' 
#' @return price of convertible
#' @export
CBprice <- function(S_0, sigma, riskFreeInterestRate, creditSpread, rateCompounding, couponRate, couponFreq, dividendProtectionRate, RDividendSchedule, conversionRatio, noConversionPeriod, americanConversionType, maturity, faceValue, redemptionPremium, softCallStartTime, softCall, softCallStrike, putStartTime, putStrike, callStartTime, callStrike, nbStepsPerYear) {
    .Call('convbond_CBprice', PACKAGE = 'convbond', S_0, sigma, riskFreeInterestRate, creditSpread, rateCompounding, couponRate, couponFreq, dividendProtectionRate, RDividendSchedule, conversionRatio, noConversionPeriod, americanConversionType, maturity, faceValue, redemptionPremium, softCallStartTime, softCall, softCallStrike, putStartTime, putStrike, callStartTime, callStrike, nbStepsPerYear)
}

#' @export
CBfindCoupon <- function(S_0, sigma, intRate0, creditSpread, rateCompounding, couponFreq, dividendProtectionRate, RDividendSchedule, conversionRatio, noConversionPeriod, americanConversionType, maturity, faceValue, redemptionPremium, softCallStartTime, softCall, softCallStrike, putStartTime, putStrike, callStartTime, callStrike, nbStepsPerYear, targetBondPrice = 1.0) {
    .Call('convbond_CBfindCoupon', PACKAGE = 'convbond', S_0, sigma, intRate0, creditSpread, rateCompounding, couponFreq, dividendProtectionRate, RDividendSchedule, conversionRatio, noConversionPeriod, americanConversionType, maturity, faceValue, redemptionPremium, softCallStartTime, softCall, softCallStrike, putStartTime, putStrike, callStartTime, callStrike, nbStepsPerYear, targetBondPrice)
}

