# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CBpriceR <- function(S_0, sigma, intRate0, creditSpread, rateCompounding, couponRate, couponFreq, dividendProtectionRate, RDividendSchedule, conversionRatio, noConversionPeriod, americanConversionType, maturity, faceValue, redemtionPremium, barrierStartTime, barrier, barrierStrike, putStartTime, putStrike, callStartTime, callStrike, nbStepsPerYear) {
    .Call('convbond_CBpriceR', PACKAGE = 'convbond', S_0, sigma, intRate0, creditSpread, rateCompounding, couponRate, couponFreq, dividendProtectionRate, RDividendSchedule, conversionRatio, noConversionPeriod, americanConversionType, maturity, faceValue, redemtionPremium, barrierStartTime, barrier, barrierStrike, putStartTime, putStrike, callStartTime, callStrike, nbStepsPerYear)
}

convBondFindCouponR <- function(S_0, sigma, intRate0, creditSpread, rateCompounding, couponFreq, dividendProtectionRate, RDividendSchedule, conversionRatio, noConversionPeriod, americanConversionType, maturity, faceValue, redemtionPremium, barrierStartTime, barrier, barrierStrike, putStartTime, putStrike, callStartTime, callStrike, nbStepsPerYear) {
    .Call('convbond_convBondFindCouponR', PACKAGE = 'convbond', S_0, sigma, intRate0, creditSpread, rateCompounding, couponFreq, dividendProtectionRate, RDividendSchedule, conversionRatio, noConversionPeriod, americanConversionType, maturity, faceValue, redemtionPremium, barrierStartTime, barrier, barrierStrike, putStartTime, putStrike, callStartTime, callStrike, nbStepsPerYear)
}

